services:

  #
  # The API gateway exposes Kibana at an external HTTPS URL
  #
  apigateway:
    image: kong/kong:3.9-ubuntu
    hostname: apigateway-internal
    ports:
      - 443:8000
    volumes:
      - ./kong.yml:/usr/local/kong/declarative/kong.yml
      - ./certs/authsamples-dev.ssl.crt:/usr/local/share/certs/authsamples-dev.ssl.crt
      - ./certs/authsamples-dev.ssl.key:/usr/local/share/certs/authsamples-dev.ssl.key
      - ./certs/authsamples-dev.ca.crt:/usr/local/share/certs/authsamples-dev.ca.crt
    environment:
      KONG_DATABASE: 'off'
      KONG_DECLARATIVE_CONFIG: '/usr/local/kong/declarative/kong.yml'
      KONG_PROXY_LISTEN: '0.0.0.0:8000 http2 ssl'
      KONG_SSL_CERT: '/usr/local/share/certs/authsamples-dev.ssl.crt'
      KONG_SSL_CERT_KEY: './usr/local/share/certs/authsamples-dev.ssl.key'
      KONG_LOG_LEVEL: 'info'

  #
  # Deploy Elasticsearch using manually configured security
  #
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.1.2
    hostname: elasticsearch-internal
    volumes:
    - ./data:/usr/share/elasticsearch/data
    environment:
      discovery.type: 'single-node'
      xpack.security.enabled: 'true'
      xpack.security.http.ssl.enabled: 'false'
      xpack.security.autoconfiguration.enabled: 'false'
      ES_JAVA_OPTS: -Xmx4g
      ELASTIC_PASSWORD: 'Password1'

  #
  # An init container used to initialize Elasticseach data and set the Kibana user account
  #
  elasticsearch-init-job:
    image: elasticjob:latest
    environment:
      ELASTIC_URL: 'http://elasticsearch-internal:9200'
      ELASTIC_USER: 'elastic'
      ELASTIC_PASSWORD: 'Password1'
      KIBANA_SYSTEM_USER: 'kibana_system'
      KIBANA_PASSWORD: 'Password1'
    depends_on:
      elasticsearch:
        condition: service_started

  #
  # Deploy Kibana with a user account different to 'elastic', to prevent startup failures
  #
  kibana:
    image: docker.elastic.co/kibana/kibana:9.1.2
    hostname: kibana-internal
    environment:
      ELASTICSEARCH_HOSTS: 'http://elasticsearch-internal:9200'
      ELASTICSEARCH_USERNAME: 'kibana_system'
      ELASTICSEARCH_PASSWORD: 'Password1'
      SERVER_PUBLICBASEURL: 'https://logs.authsamples-dev.com'
      SERVER_SSL_ENABLED: 'false'

  #
  # Deploy Filebeat to point to shares on the host computer, and with settings in the filebeat.yml file
  #
  filebeat:
    image: docker.elastic.co/beats/filebeat:9.1.2
    command: filebeat -e --strict.perms=false -c /etc/filebeat/filebeat.yml
    hostname: filebeat-internal
    volumes:
      - ./filebeat.yml:/etc/filebeat/filebeat.yml
      - ../oauth.apisample.nodejs/logs:/var/log/api
    environment:
      ELASTICSEARCH_USERNAME: 'elastic'
      ELASTICSEARCH_PASSWORD: 'Password1'
    depends_on:
      elasticsearch-init-job:
        condition: service_completed_successfully
