filebeat.inputs:
- type: filestream
  enabled: true
  id: apilogs
  paths:
  - /var/log/api/api-*.log
  parsers:
  - ndjson:
      keys_under_root: true
      add_error_key: false

output.elasticsearch:
  hosts: ['http://elasticsearch-internal:9200']
  username: elastic
  password: Password1
  index: "api-%{+yyyy.MM.dd}"
  pipelines:
  - pipeline: api

setup:
  ilm:
    enabled: false
  template:
    name: api
    pattern: api-*

processors:
- drop_fields:
    fields: ['agent', 'ecs', 'host', 'input', 'version']
